import type { App, Component } from 'vue';
import 'element-plus/dist/index.css';

import {
  ElConfigProvider,
  ElTabs,
  ElTabPane,
  ElContainer,
  ElAside,
  ElHeader,
  ElMain,
  ElTag,
  ElSkeleton,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElScrollbar,
  ElSubMenu,
  ElButton,
  ElCol,
  ElRow,
  ElSpace,
  ElDivider,
  ElCard,
  ElDropdown,
  ElDialog,
  ElMenu,
  ElMenuItem,
  ElDropdownItem,
  ElDropdownMenu,
  ElIcon,
  ElInput,
  ElCalendar,
  ElAutocomplete,
  ElForm,
  ElFormItem,
  ElLoading,
  ElPopover,
  ElPopper,
  ElTooltip,
  ElDrawer,
  ElPagination,
  ElAlert,
  ElRadioButton,
  ElRadioGroup,
  ElDescriptions,
  ElDescriptionsItem,
  ElBacktop,
  ElFooter,
  ElCheckboxGroup,
  ElCheckbox,
  ElTree,
  ElSelectV2,
  ElTransfer,
  ElSelect,
  ElOption,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElDatePicker,
  ElUpload,
  ElCollapse,
  ElCollapseItem,
  ElRadio,
  ElSteps,
  ElStep,
  ElMessage,
  ElCascader,
  ElTimePicker,
  ElCollapseTransition,
  ElTimeline,
  ElTimelineItem
} from 'element-plus';

const components = [
  ElTimeline,
  ElTimelineItem,
  ElConfigProvider,
  ElTabs,
  ElTabPane,
  ElContainer,
  ElAside,
  ElHeader,
  ElMain,
  ElTag,
  ElSkeleton,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElScrollbar,
  ElSubMenu,
  ElButton,
  ElCol,
  ElRow,
  ElSpace,
  ElDivider,
  ElCard,
  ElDropdown,
  ElDialog,
  ElMenu,
  ElMenuItem,
  ElDropdownItem,
  ElDropdownMenu,
  ElIcon,
  ElInput,
  ElCalendar,
  ElAutocomplete,
  ElForm,
  ElFormItem,
  ElPopover,
  ElPopper,
  ElTooltip,
  ElDrawer,
  ElPagination,
  ElAlert,
  ElRadioButton,
  ElRadioGroup,
  ElDescriptions,
  ElDescriptionsItem,
  ElBacktop,
  ElFooter,
  ElCheckbox,
  ElCheckboxGroup,
  ElTree,
  ElTransfer,
  ElSelectV2,
  ElSelect,
  ElOption,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElDatePicker,
  ElUpload,
  ElCollapse,
  ElCollapseItem,
  ElRadio,
  ElSteps,
  ElStep,
  ElCascader,
  ElTimePicker,
  ElCollapseTransition
];

const plugins = [ElLoading, ElMessage];

// 统一处理element第三方组件-改为思致组件
export function useElementPlus(app: App) {
  components.forEach((component: Component) => {
    app.component(component.name!, component);
  });
  plugins.forEach((plugin) => {
    app.use(plugin);
  });
}
